#Properties file for Genisys Server
motd=MCPE v0.15.10 Server
server-port=19132
server-ip=0.0.0.0
view-distance=4
max-players=20
spawn-protection=16
white-list=false
allow-flight=false
spawn-animals=true
spawn-mobs=true
difficulty=1
gamemode=0
pvp=true
generator-settings=
level-name=world
level-seed=
level-type=DEFAULT
enable-query=true
enable-rcon=false
auto-save=true

